// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReparaStoreApp.Data;

#nullable disable

namespace ReparaStoreApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250714175232_CargaInicialdeRegistros")]
    partial class CargaInicialdeRegistros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Cliente.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaEdicion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SegundoNombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEdicionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("UsuarioEdicionId");

                    b.ToTable("STO_Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Codigo = "CLI-001",
                            Correo = "juan@example.com",
                            Direccion = "Calle Principal #123",
                            FechaCreacion = new DateTime(2025, 7, 14, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(2201),
                            FechaEdicion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificacion = "0924875614",
                            Nombre = "Juan Pérez",
                            Nota = "",
                            PrimerApellido = "Pérez",
                            PrimerNombre = "Juan",
                            SegundoApellido = "Segundo",
                            SegundoNombre = "Pablo",
                            Telefono = "809-555-1234",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Codigo = "CLI-002",
                            Correo = "maria@example.com",
                            Direccion = "Avenida Libertad #456",
                            FechaCreacion = new DateTime(2025, 7, 14, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(2204),
                            FechaEdicion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificacion = "0924846591",
                            Nombre = "María Rodríguez",
                            Nota = "",
                            PrimerApellido = "Rodríguez",
                            PrimerNombre = "María",
                            SegundoApellido = "Alvarez",
                            SegundoNombre = "Lucía",
                            Telefono = "809-555-9876",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Codigo = "CLI-003",
                            Correo = "carlos@example.com",
                            Direccion = "Calle Las Flores #789",
                            FechaCreacion = new DateTime(2025, 7, 14, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(2207),
                            FechaEdicion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1982, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Identificacion = "0924859632",
                            Nombre = "Carlos Sánchez",
                            Nota = "",
                            PrimerApellido = "Sánchez",
                            PrimerNombre = "Carlos",
                            SegundoApellido = "González",
                            SegundoNombre = "Tyron",
                            Telefono = "829-555-4567",
                            UsuarioCreadorId = 1
                        });
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Dispositivo.Dispositivos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaEdicion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEdicionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("UsuarioEdicionId");

                    b.ToTable("STO_Dispositivos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            ClienteId = 1,
                            Codigo = "DIS-001",
                            Descripcion = "",
                            Estado = "Ingresado",
                            FechaCreacion = new DateTime(2025, 7, 14, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(2235),
                            FechaEdicion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Apple",
                            Modelo = "iPhone X",
                            Nombre = "iPhone X de Juan",
                            NumeroSerie = "A123456789",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            ClienteId = 2,
                            Codigo = "DIS-002",
                            Descripcion = "",
                            Estado = "Ingresado",
                            FechaCreacion = new DateTime(2025, 7, 14, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(2238),
                            FechaEdicion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Samsung",
                            Modelo = "Galaxy S21",
                            Nombre = "Samsung Galaxy S21 de María",
                            NumeroSerie = "SM123456789",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            ClienteId = 3,
                            Codigo = "DIS-003",
                            Descripcion = "",
                            Estado = "EnReparacion",
                            FechaCreacion = new DateTime(2025, 7, 14, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(2239),
                            FechaEdicion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Apple",
                            Modelo = "iPad Pro 12.9\"",
                            Nombre = "iPad Pro de Carlos",
                            NumeroSerie = "IPD987654321",
                            UsuarioCreadorId = 1
                        });
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Inventario.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("StockMaximo")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("STO_Inventario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = false,
                            Cantidad = 100,
                            ProductoId = 1,
                            StockMaximo = 400,
                            StockMinimo = 5
                        },
                        new
                        {
                            Id = 2,
                            Activo = false,
                            Cantidad = 150,
                            ProductoId = 2,
                            StockMaximo = 300,
                            StockMinimo = 20
                        },
                        new
                        {
                            Id = 3,
                            Activo = false,
                            Cantidad = 200,
                            ProductoId = 4,
                            StockMaximo = 500,
                            StockMinimo = 15
                        },
                        new
                        {
                            Id = 4,
                            Activo = false,
                            Cantidad = 500,
                            ProductoId = 5,
                            StockMaximo = 800,
                            StockMinimo = 10
                        });
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Inventario.ItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEdicion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("TieneIVA")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEdicionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("UsuarioEdicionId");

                    b.ToTable("STO_Items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Codigo = "PROD-001",
                            Descripcion = "",
                            FechaCreacion = new DateTime(2025, 7, 14, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(1923),
                            Nombre = "Pantalla iPhone X",
                            Nota = "",
                            Precio = 120.00m,
                            TieneIVA = true,
                            Tipo = "Producto",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Codigo = "PROD-002",
                            Descripcion = "",
                            FechaCreacion = new DateTime(2025, 7, 14, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(1925),
                            Nombre = "Batería Samsung S20",
                            Nota = "",
                            Precio = 45.00m,
                            TieneIVA = true,
                            Tipo = "Producto",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Codigo = "SERV-001",
                            Descripcion = "",
                            FechaCreacion = new DateTime(2025, 7, 14, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(1926),
                            Nombre = "Cambio de pantalla",
                            Nota = "",
                            Precio = 50.00m,
                            TieneIVA = true,
                            Tipo = "Servicio",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Codigo = "PROD-003",
                            Descripcion = "",
                            FechaCreacion = new DateTime(2025, 7, 14, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(1927),
                            Nombre = "Cargador USB-C",
                            Nota = "",
                            Precio = 15.00m,
                            TieneIVA = true,
                            Tipo = "Producto",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Codigo = "PROD-004",
                            Descripcion = "",
                            FechaCreacion = new DateTime(2025, 7, 14, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(1929),
                            Nombre = "Cable Lightning",
                            Nota = "",
                            Precio = 10.00m,
                            TieneIVA = true,
                            Tipo = "Producto",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Codigo = "SERV-002",
                            Descripcion = "",
                            FechaCreacion = new DateTime(2025, 7, 14, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(1930),
                            Nombre = "Cambio de conector de carga",
                            Nota = "",
                            Precio = 35.00m,
                            TieneIVA = true,
                            Tipo = "Servicio",
                            UsuarioCreadorId = 1
                        });
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Inventario.Kardex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEdicion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEdicionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("UsuarioEdicionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("STO_Kardex", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 100,
                            Fecha = new DateTime(2025, 7, 9, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(2132),
                            FechaCreacion = new DateTime(2025, 7, 9, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(2142),
                            Notas = "Carga inicial Productos",
                            PrecioUnitario = 120.00m,
                            ProductoId = 1,
                            Tipo = "Ingreso",
                            Total = 12000.00m,
                            UsuarioCreadorId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 150,
                            Fecha = new DateTime(2025, 7, 11, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(2154),
                            FechaCreacion = new DateTime(2025, 7, 11, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(2156),
                            Notas = "Carga inicial Productos",
                            PrecioUnitario = 45.00m,
                            ProductoId = 2,
                            Tipo = "Ingreso",
                            Total = 6750.00m,
                            UsuarioCreadorId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 200,
                            Fecha = new DateTime(2025, 7, 12, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(2157),
                            FechaCreacion = new DateTime(2025, 7, 12, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(2158),
                            Notas = "Carga inicial Productos",
                            PrecioUnitario = 15.00m,
                            ProductoId = 4,
                            Tipo = "Ingreso",
                            Total = 3000.00m,
                            UsuarioCreadorId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 500,
                            Fecha = new DateTime(2025, 7, 13, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(2159),
                            FechaCreacion = new DateTime(2025, 7, 13, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(2161),
                            Notas = "Carga inicial Productos",
                            PrecioUnitario = 10.00m,
                            ProductoId = 5,
                            Tipo = "Ingreso",
                            Total = 5000.00m,
                            UsuarioCreadorId = 1,
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Security.Params", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaEdicion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEdicionId")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("UsuarioEdicionId");

                    b.ToTable("SYS_PARAMETROS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = false,
                            Code = "SYS-IVA",
                            FechaCreacion = new DateTime(2025, 7, 14, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(2258),
                            Name = "IVA para la venta",
                            Nota = "IVA para la venta",
                            UsuarioCreadorId = 1,
                            Valor = "15"
                        });
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Security.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SEC_ROLES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Acceso total al sistema",
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Manejo de transacciones financieras",
                            Name = "Cajero"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Reparación y mantenimiento",
                            Name = "Técnico"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Usuario final del sistema",
                            Name = "Cliente"
                        });
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Security.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SEC_USUARIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "001",
                            CreatedAt = new DateTime(2025, 7, 14, 17, 52, 28, 717, DateTimeKind.Utc).AddTicks(1452),
                            Email = "admin@reparastore.com",
                            FirstName = "admin",
                            IsActive = true,
                            LastName = "admin",
                            Name = "admin",
                            Note = "Usuario Administrador",
                            PasswordHash = "$2a$11$aIIpAZ.kxu45ZPQe6DZKS.OWNbo4vvAOLV2KTf2RXTkVMG/.I41AC",
                            PhoneNumber = "1234567890"
                        });
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Security.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("SEC_USUARIO_ROLES", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            Id = 0
                        });
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Store.Reparacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("CajeroId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoEstimado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CostoFinal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DispositivoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaEdicion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaReparado")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NotasIngreso")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("NotasReparado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TecnicoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioAprobacionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEdicionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioReparadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CajeroId");

                    b.HasIndex("DispositivoId");

                    b.HasIndex("TecnicoId");

                    b.HasIndex("UsuarioAprobacionId");

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("UsuarioEdicionId");

                    b.HasIndex("UsuarioReparadoId");

                    b.ToTable("STO_Reparaciones", (string)null);
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Store.ReparacionDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEdicion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ReparacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TasaIVA")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalIVA")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEdicionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ReparacionId");

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("UsuarioEdicionId");

                    b.ToTable("STO_Reparaciones_Dt", (string)null);
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Ventas.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaEdicion")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ReparacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEdicionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("ReparacionId")
                        .IsUnique();

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("UsuarioEdicionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("STO_Facturas", (string)null);
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Ventas.FacturaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEdicion")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TasaIVA")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalIVA")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEdicionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("UsuarioEdicionId");

                    b.ToTable("STO_Facturas_Dt", (string)null);
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Cliente.Clientes", b =>
                {
                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioEdicion")
                        .WithMany()
                        .HasForeignKey("UsuarioEdicionId");

                    b.Navigation("UsuarioCreador");

                    b.Navigation("UsuarioEdicion");
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Dispositivo.Dispositivos", b =>
                {
                    b.HasOne("ReparaStoreApp.Entities.Models.Cliente.Clientes", "Cliente")
                        .WithMany("Dispositivos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioEdicion")
                        .WithMany()
                        .HasForeignKey("UsuarioEdicionId");

                    b.Navigation("Cliente");

                    b.Navigation("UsuarioCreador");

                    b.Navigation("UsuarioEdicion");
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Inventario.Inventario", b =>
                {
                    b.HasOne("ReparaStoreApp.Entities.Models.Inventario.ItemEntity", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Inventario.ItemEntity", b =>
                {
                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioEdicion")
                        .WithMany()
                        .HasForeignKey("UsuarioEdicionId");

                    b.Navigation("UsuarioCreador");

                    b.Navigation("UsuarioEdicion");
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Inventario.Kardex", b =>
                {
                    b.HasOne("ReparaStoreApp.Entities.Models.Inventario.ItemEntity", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioEdicion")
                        .WithMany()
                        .HasForeignKey("UsuarioEdicionId");

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioCreador");

                    b.Navigation("UsuarioEdicion");
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Security.Params", b =>
                {
                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioEdicion")
                        .WithMany()
                        .HasForeignKey("UsuarioEdicionId");

                    b.Navigation("UsuarioCreador");

                    b.Navigation("UsuarioEdicion");
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Security.UserRole", b =>
                {
                    b.HasOne("ReparaStoreApp.Entities.Models.Security.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Store.Reparacion", b =>
                {
                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "Cajero")
                        .WithMany()
                        .HasForeignKey("CajeroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReparaStoreApp.Entities.Models.Dispositivo.Dispositivos", "Dispositivo")
                        .WithMany("Reparaciones")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioAprobacion")
                        .WithMany()
                        .HasForeignKey("UsuarioAprobacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioEdicion")
                        .WithMany()
                        .HasForeignKey("UsuarioEdicionId");

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioReparado")
                        .WithMany()
                        .HasForeignKey("UsuarioReparadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cajero");

                    b.Navigation("Dispositivo");

                    b.Navigation("Tecnico");

                    b.Navigation("UsuarioAprobacion");

                    b.Navigation("UsuarioCreador");

                    b.Navigation("UsuarioEdicion");

                    b.Navigation("UsuarioReparado");
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Store.ReparacionDetalle", b =>
                {
                    b.HasOne("ReparaStoreApp.Entities.Models.Inventario.ItemEntity", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Store.Reparacion", "Reparacion")
                        .WithMany("Detalles")
                        .HasForeignKey("ReparacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioEdicion")
                        .WithMany()
                        .HasForeignKey("UsuarioEdicionId");

                    b.Navigation("Item");

                    b.Navigation("Reparacion");

                    b.Navigation("UsuarioCreador");

                    b.Navigation("UsuarioEdicion");
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Ventas.Factura", b =>
                {
                    b.HasOne("ReparaStoreApp.Entities.Models.Cliente.Clientes", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Store.Reparacion", "Reparacion")
                        .WithOne("Factura")
                        .HasForeignKey("ReparaStoreApp.Entities.Models.Ventas.Factura", "ReparacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioEdicion")
                        .WithMany()
                        .HasForeignKey("UsuarioEdicionId");

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Reparacion");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioCreador");

                    b.Navigation("UsuarioEdicion");
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Ventas.FacturaDetalle", b =>
                {
                    b.HasOne("ReparaStoreApp.Entities.Models.Ventas.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Inventario.ItemEntity", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReparaStoreApp.Entities.Models.Security.User", "UsuarioEdicion")
                        .WithMany()
                        .HasForeignKey("UsuarioEdicionId");

                    b.Navigation("Factura");

                    b.Navigation("Producto");

                    b.Navigation("UsuarioCreador");

                    b.Navigation("UsuarioEdicion");
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Cliente.Clientes", b =>
                {
                    b.Navigation("Dispositivos");
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Dispositivo.Dispositivos", b =>
                {
                    b.Navigation("Reparaciones");
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Security.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Security.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Store.Reparacion", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Factura")
                        .IsRequired();
                });

            modelBuilder.Entity("ReparaStoreApp.Entities.Models.Ventas.Factura", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
